name: Validate Name Changes List

on:
  push:
    branches: [master]
    paths:
      # Necessary when the name_changes.txt list is updated or any unit file.
      - "megamek/data/mechfiles/**.blk"
      - "megamek/data/mechfiles/**.mtf"
      - "megamek/data/mechfiles/name_changes.txt"
  pull_request:
    branches: [master]
    paths:
      - "megamek/data/mechfiles/**.blk"
      - "megamek/data/mechfiles/**.mtf"
      - "megamek/data/mechfiles/name_changes.txt"

jobs:
  name_changes_validator:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java-distribution: [temurin]
        java-version: [17]

    steps:
      - uses: actions/checkout@v4

      - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Boards
        working-directory: megamek
        run: ./gradlew nameChangesValidator
